// source: mra.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var common_common_pb = require('./common/common_pb.js');
goog.object.extend(proto, common_common_pb);
goog.exportSymbol('proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.mra.MRADetails', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.mra.scheduleMRARequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.mra.MRADetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.mra.MRADetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.mra.MRADetails.displayName = 'proto.ai.nworx.api.proto.mra.MRADetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.displayName = 'proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.mra.scheduleMRARequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.mra.scheduleMRARequest.displayName = 'proto.ai.nworx.api.proto.mra.scheduleMRARequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.displayName = 'proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.displayName = 'proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.mra.MRADetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.mra.MRADetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.MRADetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mraid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.mra.MRADetails;
  return proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.mra.MRADetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMraid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.mra.MRADetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMraid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.MRADetails} returns this
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string mraId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.getMraid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.MRADetails} returns this
 */
proto.ai.nworx.api.proto.mra.MRADetails.prototype.setMraid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    mradetails: (f = msg.getMradetails()) && proto.ai.nworx.api.proto.mra.MRADetails.toObject(includeInstance, f),
    assessorid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    role: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest;
  return proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.nworx.api.proto.mra.MRADetails;
      reader.readMessage(value,proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader);
      msg.setMradetails(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssessorid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMradetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter
    );
  }
  f = message.getAssessorid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional MRADetails mraDetails = 1;
 * @return {?proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.getMradetails = function() {
  return /** @type{?proto.ai.nworx.api.proto.mra.MRADetails} */ (
    jspb.Message.getWrapperField(this, proto.ai.nworx.api.proto.mra.MRADetails, 1));
};


/**
 * @param {?proto.ai.nworx.api.proto.mra.MRADetails|undefined} value
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} returns this
*/
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.setMradetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} returns this
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.clearMradetails = function() {
  return this.setMradetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.hasMradetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string assessorId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.getAssessorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} returns this
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.setAssessorid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string role = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} returns this
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.setRole = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} returns this
 */
proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.mra.scheduleMRARequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    mradetails: (f = msg.getMradetails()) && proto.ai.nworx.api.proto.mra.MRADetails.toObject(includeInstance, f),
    startdate: jspb.Message.getFieldWithDefault(msg, 2, 0),
    enddate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    personalmsgsMap: (f = msg.getPersonalmsgsMap()) ? f.toObject(includeInstance, undefined) : [],
    generalmessage: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.mra.scheduleMRARequest;
  return proto.ai.nworx.api.proto.mra.scheduleMRARequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.nworx.api.proto.mra.MRADetails;
      reader.readMessage(value,proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader);
      msg.setMradetails(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartdate(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEnddate(value);
      break;
    case 4:
      var value = msg.getPersonalmsgsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGeneralmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.mra.scheduleMRARequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMradetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter
    );
  }
  f = message.getStartdate();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEnddate();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPersonalmsgsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getGeneralmessage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional MRADetails mraDetails = 1;
 * @return {?proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.getMradetails = function() {
  return /** @type{?proto.ai.nworx.api.proto.mra.MRADetails} */ (
    jspb.Message.getWrapperField(this, proto.ai.nworx.api.proto.mra.MRADetails, 1));
};


/**
 * @param {?proto.ai.nworx.api.proto.mra.MRADetails|undefined} value
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
*/
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.setMradetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.clearMradetails = function() {
  return this.setMradetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.hasMradetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 startDate = 2;
 * @return {number}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.getStartdate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.setStartdate = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 endDate = 3;
 * @return {number}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.getEnddate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.setEnddate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * map<string, string> personalMsgs = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.getPersonalmsgsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.clearPersonalmsgsMap = function() {
  this.getPersonalmsgsMap().clear();
  return this;
};


/**
 * optional string generalMessage = 5;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.getGeneralmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.scheduleMRARequest.prototype.setGeneralmessage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    mradetails: (f = msg.getMradetails()) && proto.ai.nworx.api.proto.mra.MRADetails.toObject(includeInstance, f),
    role: jspb.Message.getFieldWithDefault(msg, 2, ""),
    enable: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest;
  return proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.nworx.api.proto.mra.MRADetails;
      reader.readMessage(value,proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader);
      msg.setMradetails(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMradetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter
    );
  }
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEnable();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional MRADetails mraDetails = 1;
 * @return {?proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.getMradetails = function() {
  return /** @type{?proto.ai.nworx.api.proto.mra.MRADetails} */ (
    jspb.Message.getWrapperField(this, proto.ai.nworx.api.proto.mra.MRADetails, 1));
};


/**
 * @param {?proto.ai.nworx.api.proto.mra.MRADetails|undefined} value
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} returns this
*/
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.setMradetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} returns this
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.clearMradetails = function() {
  return this.setMradetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.hasMradetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string role = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} returns this
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.setRole = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool enable = 3;
 * @return {boolean}
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.getEnable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} returns this
 */
proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest.prototype.setEnable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    mradetails: (f = msg.getMradetails()) && proto.ai.nworx.api.proto.mra.MRADetails.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, ""),
    designation: jspb.Message.getFieldWithDefault(msg, 4, ""),
    role: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest;
  return proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.nworx.api.proto.mra.MRADetails;
      reader.readMessage(value,proto.ai.nworx.api.proto.mra.MRADetails.deserializeBinaryFromReader);
      msg.setMradetails(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesignation(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMradetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.nworx.api.proto.mra.MRADetails.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDesignation();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional MRADetails mraDetails = 1;
 * @return {?proto.ai.nworx.api.proto.mra.MRADetails}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.getMradetails = function() {
  return /** @type{?proto.ai.nworx.api.proto.mra.MRADetails} */ (
    jspb.Message.getWrapperField(this, proto.ai.nworx.api.proto.mra.MRADetails, 1));
};


/**
 * @param {?proto.ai.nworx.api.proto.mra.MRADetails|undefined} value
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
*/
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.setMradetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.clearMradetails = function() {
  return this.setMradetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.hasMradetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string designation = 4;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.getDesignation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.setDesignation = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string role = 5;
 * @return {string}
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} returns this
 */
proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest.prototype.setRole = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.ai.nworx.api.proto.mra);
