/**
 * @fileoverview gRPC-Web generated client stub for ai.nworx.api.proto.mra
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.22.2
// source: mra.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var common_common_pb = require('./common/common_pb.js')
const proto = {};
proto.ai = {};
proto.ai.nworx = {};
proto.ai.nworx.api = {};
proto.ai.nworx.api.proto = {};
proto.ai.nworx.api.proto.mra = require('./mra_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.nworx.api.proto.mra.MRADetails,
 *   !proto.ai.nworx.api.proto.common.ResponseProto>}
 */
const methodDescriptor_MRAService_fetchMRADetails = new grpc.web.MethodDescriptor(
  '/ai.nworx.api.proto.mra.MRAService/fetchMRADetails',
  grpc.web.MethodType.UNARY,
  proto.ai.nworx.api.proto.mra.MRADetails,
  common_common_pb.ResponseProto,
  /**
   * @param {!proto.ai.nworx.api.proto.mra.MRADetails} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_common_pb.ResponseProto.deserializeBinary
);


/**
 * @param {!proto.ai.nworx.api.proto.mra.MRADetails} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.nworx.api.proto.common.ResponseProto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.nworx.api.proto.common.ResponseProto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient.prototype.fetchMRADetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/fetchMRADetails',
      request,
      metadata || {},
      methodDescriptor_MRAService_fetchMRADetails,
      callback);
};


/**
 * @param {!proto.ai.nworx.api.proto.mra.MRADetails} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.nworx.api.proto.common.ResponseProto>}
 *     Promise that resolves to the response
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient.prototype.fetchMRADetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/fetchMRADetails',
      request,
      metadata || {},
      methodDescriptor_MRAService_fetchMRADetails);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest,
 *   !proto.ai.nworx.api.proto.common.ResponseProto>}
 */
const methodDescriptor_MRAService_updateMRAAssessor = new grpc.web.MethodDescriptor(
  '/ai.nworx.api.proto.mra.MRAService/updateMRAAssessor',
  grpc.web.MethodType.UNARY,
  proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest,
  common_common_pb.ResponseProto,
  /**
   * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_common_pb.ResponseProto.deserializeBinary
);


/**
 * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.nworx.api.proto.common.ResponseProto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.nworx.api.proto.common.ResponseProto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient.prototype.updateMRAAssessor =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/updateMRAAssessor',
      request,
      metadata || {},
      methodDescriptor_MRAService_updateMRAAssessor,
      callback);
};


/**
 * @param {!proto.ai.nworx.api.proto.mra.updateMRAAssessorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.nworx.api.proto.common.ResponseProto>}
 *     Promise that resolves to the response
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient.prototype.updateMRAAssessor =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/updateMRAAssessor',
      request,
      metadata || {},
      methodDescriptor_MRAService_updateMRAAssessor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest,
 *   !proto.ai.nworx.api.proto.common.ResponseProto>}
 */
const methodDescriptor_MRAService_updateAssessee = new grpc.web.MethodDescriptor(
  '/ai.nworx.api.proto.mra.MRAService/updateAssessee',
  grpc.web.MethodType.UNARY,
  proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest,
  common_common_pb.ResponseProto,
  /**
   * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_common_pb.ResponseProto.deserializeBinary
);


/**
 * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.nworx.api.proto.common.ResponseProto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.nworx.api.proto.common.ResponseProto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient.prototype.updateAssessee =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/updateAssessee',
      request,
      metadata || {},
      methodDescriptor_MRAService_updateAssessee,
      callback);
};


/**
 * @param {!proto.ai.nworx.api.proto.mra.UpdateAssesseeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.nworx.api.proto.common.ResponseProto>}
 *     Promise that resolves to the response
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient.prototype.updateAssessee =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/updateAssessee',
      request,
      metadata || {},
      methodDescriptor_MRAService_updateAssessee);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.nworx.api.proto.mra.scheduleMRARequest,
 *   !proto.ai.nworx.api.proto.common.ResponseProto>}
 */
const methodDescriptor_MRAService_scheduleMRA = new grpc.web.MethodDescriptor(
  '/ai.nworx.api.proto.mra.MRAService/scheduleMRA',
  grpc.web.MethodType.UNARY,
  proto.ai.nworx.api.proto.mra.scheduleMRARequest,
  common_common_pb.ResponseProto,
  /**
   * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_common_pb.ResponseProto.deserializeBinary
);


/**
 * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.nworx.api.proto.common.ResponseProto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.nworx.api.proto.common.ResponseProto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient.prototype.scheduleMRA =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/scheduleMRA',
      request,
      metadata || {},
      methodDescriptor_MRAService_scheduleMRA,
      callback);
};


/**
 * @param {!proto.ai.nworx.api.proto.mra.scheduleMRARequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.nworx.api.proto.common.ResponseProto>}
 *     Promise that resolves to the response
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient.prototype.scheduleMRA =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/scheduleMRA',
      request,
      metadata || {},
      methodDescriptor_MRAService_scheduleMRA);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest,
 *   !proto.ai.nworx.api.proto.common.ResponseProto>}
 */
const methodDescriptor_MRAService_addNewPersonToMRA = new grpc.web.MethodDescriptor(
  '/ai.nworx.api.proto.mra.MRAService/addNewPersonToMRA',
  grpc.web.MethodType.UNARY,
  proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest,
  common_common_pb.ResponseProto,
  /**
   * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_common_pb.ResponseProto.deserializeBinary
);


/**
 * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.nworx.api.proto.common.ResponseProto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.nworx.api.proto.common.ResponseProto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.nworx.api.proto.mra.MRAServiceClient.prototype.addNewPersonToMRA =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/addNewPersonToMRA',
      request,
      metadata || {},
      methodDescriptor_MRAService_addNewPersonToMRA,
      callback);
};


/**
 * @param {!proto.ai.nworx.api.proto.mra.AddNewPersonToMRARequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.nworx.api.proto.common.ResponseProto>}
 *     Promise that resolves to the response
 */
proto.ai.nworx.api.proto.mra.MRAServicePromiseClient.prototype.addNewPersonToMRA =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.nworx.api.proto.mra.MRAService/addNewPersonToMRA',
      request,
      metadata || {},
      methodDescriptor_MRAService_addNewPersonToMRA);
};


module.exports = proto.ai.nworx.api.proto.mra;

