export const AUTH_STATES = {
  SIGNIN: "SIGNIN",
  SIGNUP: "SIGNUP",
};

export const AUTH_TAB_TYPES = {
  EMAIL: "EMAIL",
  PHONE: "PHONE",
};

export const AUTH_OPTION_TYPES = {
  EMAIL_SIGNUP: "EMAIL_SIGNUP",
  OTP_SIGNUP: "OTP_SIGNUP",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  EMAIL_VERIFICATION_PENDING: "EMAIL_VERIFICATION_PENDING",
  PASSWORD_LINK: "PASSWORD_LINK",
  RESET_PASSWORD: "RESET_PASSWORD",
  OTP_VERIFICATION: "OTP_VERIFICATION",
  MULTI_FACTOR_AUTH: "MULTI_FACTOR_AUTH",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  OTP_SIGN_IN: "OTP_SIGN_IN",
};

export const MANAGER_VIEW_STATE = {
  LP: "LP",
  MANAGER: "MANAGER",
  JP: "JP",
  EXPERT: "EXPERT",
  REPORT_VIEWER:"REPORT_VIEWER"
};
