// source: worksheet-ai.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var common_common_pb = require('./common/common_pb.js');
goog.object.extend(proto, common_common_pb);
goog.exportSymbol('proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest', null, global);
goog.exportSymbol('proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.displayName = 'proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.displayName = 'proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.displayName = 'proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.displayName = 'proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    worksheetid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    programid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    qp: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest;
  return proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorksheetid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProgramid(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setQp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorksheetid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProgramid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getQp();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string worksheetId = 1;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.getWorksheetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.setWorksheetid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string userId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string programId = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.getProgramid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.setProgramid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool qp = 4;
 * @return {boolean}
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.getQp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.FetchWorksheetAIRatingRequest.prototype.setQp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    programid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userworksheetid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    goalname: jspb.Message.getFieldWithDefault(msg, 4, ""),
    milestonename: jspb.Message.getFieldWithDefault(msg, 5, ""),
    question: jspb.Message.getFieldWithDefault(msg, 6, ""),
    answer: jspb.Message.getFieldWithDefault(msg, 7, ""),
    sectionid: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest;
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProgramid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserworksheetid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setGoalname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMilestonename(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestion(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnswer(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSectionid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProgramid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserworksheetid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGoalname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMilestonename();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getQuestion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAnswer();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSectionid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string programId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getProgramid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setProgramid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userWorksheetId = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getUserworksheetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setUserworksheetid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string goalName = 4;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getGoalname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setGoalname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string milestoneName = 5;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getMilestonename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setMilestonename = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string question = 6;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getQuestion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setQuestion = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string answer = 7;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getAnswer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setAnswer = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string sectionId = 8;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.getSectionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForQuestionRequest.prototype.setSectionid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    programid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userworksheetid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    goalname: jspb.Message.getFieldWithDefault(msg, 4, ""),
    milestonename: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sectionid: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest;
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProgramid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserworksheetid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setGoalname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMilestonename(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSectionid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProgramid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserworksheetid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGoalname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMilestonename();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSectionid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string programId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getProgramid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setProgramid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userWorksheetId = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getUserworksheetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setUserworksheetid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string goalName = 4;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getGoalname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setGoalname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string milestoneName = 5;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getMilestonename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setMilestonename = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string sectionId = 6;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.getSectionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForSectionRequest.prototype.setSectionid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    programid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userworksheetid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    goalname: jspb.Message.getFieldWithDefault(msg, 4, ""),
    milestonename: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest;
  return proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProgramid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserworksheetid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setGoalname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMilestonename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProgramid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserworksheetid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGoalname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMilestonename();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string programId = 2;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.getProgramid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.setProgramid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userWorksheetId = 3;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.getUserworksheetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.setUserworksheetid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string goalName = 4;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.getGoalname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.setGoalname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string milestoneName = 5;
 * @return {string}
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.getMilestonename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest} returns this
 */
proto.ai.nworx.api.proto.worksheetai.AIFeedbackForPrepRequest.prototype.setMilestonename = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.ai.nworx.api.proto.worksheetai);
